alert(Math.min(2, 3.7, -5, 9, 1));
alert(Math.max(2, 3.7, -5, 9, 1));
alert(Math.abs(3.7));
alert(Math.floor(3.3));
alert(Math.ceil(3.3));
alert(Math.pow(2,6));
alert(Math.sqrt(4));
alert(Math.random() * 10);
var n = Math.floor(Math.random() * 10 + 1);
alert(n);
alert(Math.exp(3));
alert(Math.log(3));
alert(Math.sin(3));
alert(Math.cos(3));
alert(Math.tan(3));
alert(Math.asin(0));
alert(Math.acos(0));
alert(Math.atan(0));
alert(Math.atan2(1,1));